#!/usr/bin/env bash
# Shared config loader for the container build/run/cleanup scripts.
#
# Sources containerconf/.env (generated by ./setup.sh) and applies defaults,
# so no script hardcodes host paths, a UID, a runtime, or a port list.
#
# Usage (top of every script):
#   SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
#   source "$SCRIPT_DIR/config.sh"

set -euo pipefail

CONF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# The .env is machine-specific (paths, UID, ports) and must never be committed.
if [ -f "$CONF_DIR/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$CONF_DIR/.env"
  set +a
else
  echo "No containerconf/.env found." >&2
  echo "Run containerconf/setup.sh once to generate it for this machine." >&2
  exit 1
fi

# --- defaults (accept the generated values or fall back if unset) ----------
: "${XPAL_RUNTIME:=}"
: "${XPAL_IMAGE:=xpal-claudia}"
: "${XPAL_CONTAINER:=xpal-dev}"
: "${XPAL_CONTAINER_REMOTE:=xpal-dev-remote}"
: "${XPAL_HOST_SRC:=$HOME/xpal-src}"
: "${XPAL_HOST_DATA:=$HOME/xpal-data}"
: "${XPAL_HOST_AUTH:=$HOME/xpal-auth}"
: "${XPAL_HOST_UID:=$(id -u)}"
: "${XPAL_PORTS:=5001:5001 8001:8001 8080:8080}"
: "${XPAL_HOST_REMOTE_DIR:=}"

# Pick a runtime if setup didn't pin one: prefer podman, fall back to docker.
if [ -z "$XPAL_RUNTIME" ]; then
  if command -v podman >/dev/null 2>&1; then
    XPAL_RUNTIME=podman
  elif command -v docker >/dev/null 2>&1; then
    XPAL_RUNTIME=docker
  else
    echo "No container runtime found (need podman or docker on PATH)." >&2
    exit 1
  fi
fi

# Expand the space-separated port list into `-p host:container` args.
PORT_ARGS=()
for p in $XPAL_PORTS; do
  PORT_ARGS+=( -p "$p" )
done
