#!/usr/bin/env bash
# Guided, per-machine setup for the container environment.
#
# Prompts for each customization point (defaults shown in brackets), creates
# the host folders, and writes containerconf/.env, which every run/build/
# cleanup script sources. Safe to re-run at any time — it only regenerates
# .env and creates missing folders; it never touches existing containers.
#
#   ./setup.sh            interactive wizard
#   ./setup.sh --yes      non-interactive (use env vars above / defaults)
#
# For a non-interactive run you can pre-set any of the values, e.g.:
#   XPAL_HOST_SRC="$HOME/code" XPAL_PORTS="8000:8000" ./setup.sh --yes

set -euo pipefail

CONF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$CONF_DIR/.env"

ASSUME_YES=0
if [ "${1:-}" = "--yes" ]; then
  ASSUME_YES=1
fi

# Pick a sensible runtime default based on what's installed.
detect_runtime() {
  if command -v podman >/dev/null 2>&1; then
    echo "podman"
  elif command -v docker >/dev/null 2>&1; then
    echo "docker"
  else
    echo "podman"
  fi
}

# prompt VARNAME DEFAULT MESSAGE — reads a value, keeps DEFAULT on empty input.
prompt() {
  local _name="$1" _default="$2" _msg="$3" _val
  if [ "$ASSUME_YES" = "1" ]; then
    # Non-interactive: keep the caller's env value if set, else the default.
    eval "_val=\${$_name:-$_default}"
    eval "$_name=\$_val"
    return
  fi
  printf '%s [%s]: ' "$_msg" "$_default"
  read -r _val
  eval "$_name=\${_val:-$_default}"
}

# --- defaults -------------------------------------------------------------
DEFAULT_UID="$(id -u)"
DEFAULT_RUNTIME="$(detect_runtime)"
DEFAULT_REMOTE="${XPAL_HOST_REMOTE_DIR:-}"

XPAL_RUNTIME="${XPAL_RUNTIME:-$DEFAULT_RUNTIME}"
XPAL_IMAGE="${XPAL_IMAGE:-xpal-claudia}"
XPAL_CONTAINER="${XPAL_CONTAINER:-xpal-dev}"
XPAL_CONTAINER_REMOTE="${XPAL_CONTAINER_REMOTE:-xpal-dev-remote}"
XPAL_HOST_SRC="${XPAL_HOST_SRC:-$HOME/xpal-src}"
XPAL_HOST_DATA="${XPAL_HOST_DATA:-$HOME/xpal-data}"
XPAL_HOST_AUTH="${XPAL_HOST_AUTH:-$HOME/xpal-auth}"
XPAL_HOST_UID="${XPAL_HOST_UID:-$DEFAULT_UID}"
XPAL_PORTS="${XPAL_PORTS:-5001:5001 8001:8001 8080:8080}"

echo "== xpal-claudia setup =="
echo "Answer each question (empty keeps the default in brackets)."
echo
prompt XPAL_RUNTIME          "$XPAL_RUNTIME"          "Container runtime"
prompt XPAL_IMAGE             "$XPAL_IMAGE"             "Image name"
prompt XPAL_CONTAINER         "$XPAL_CONTAINER"         "Day-to-day container name"
prompt XPAL_CONTAINER_REMOTE  "$XPAL_CONTAINER_REMOTE"  "Day-to-day+remote container name"
prompt XPAL_HOST_SRC          "$XPAL_HOST_SRC"          "Host folder for code      "
prompt XPAL_HOST_DATA         "$XPAL_HOST_DATA"         "Host folder for data      "
prompt XPAL_HOST_AUTH         "$XPAL_HOST_AUTH"         "Host folder for credentials"
prompt XPAL_HOST_UID          "$XPAL_HOST_UID"          "Host user UID (id -u)"
prompt XPAL_PORTS             "$XPAL_PORTS"             "Published ports (host:container, space-separated)"
prompt XPAL_HOST_REMOTE_DIR   "$DEFAULT_REMOTE"         "Optional synced remote folder (blank = none)"

# Resolve tilde/relative dirs to absolute paths for the .env and folder creation.
resolve() { case "$1" in /*) echo "$1";; *) echo "$(cd "$1" && pwd)";; esac; }
XPAL_HOST_SRC="$(resolve "$XPAL_HOST_SRC")"
XPAL_HOST_DATA="$(resolve "$XPAL_HOST_DATA")"
XPAL_HOST_AUTH="$(resolve "$XPAL_HOST_AUTH")"

# Validate the UID looks numeric before writing it.
case "$XPAL_HOST_UID" in
  ''|*[!0-9]*) echo "Error: XPAL_HOST_UID must be a number, got '$XPAL_HOST_UID'." >&2; exit 1;;
esac

# --- write the config -----------------------------------------------------
cat > "$ENV_FILE" <<EOF
# Generated by containerconf/setup.sh on $(date '+%Y-%m-%d %H:%M:%S').
# Machine-specific — do not commit. Re-run ./setup.sh to regenerate.

XPAL_RUNTIME=$XPAL_RUNTIME
XPAL_IMAGE=$XPAL_IMAGE
XPAL_CONTAINER=$XPAL_CONTAINER
XPAL_CONTAINER_REMOTE=$XPAL_CONTAINER_REMOTE
XPAL_HOST_SRC=$XPAL_HOST_SRC
XPAL_HOST_DATA=$XPAL_HOST_DATA
XPAL_HOST_AUTH=$XPAL_HOST_AUTH
XPAL_HOST_UID=$XPAL_HOST_UID
XPAL_PORTS="$XPAL_PORTS"
XPAL_HOST_REMOTE_DIR="$XPAL_HOST_REMOTE_DIR"
EOF

# --- create the host folders ----------------------------------------------
for d in "$XPAL_HOST_SRC" "$XPAL_HOST_DATA" "$XPAL_HOST_AUTH"; do
  if [ -n "$d" ]; then
    mkdir -p "$d"
  fi
done

echo
echo "Wrote $ENV_FILE"
echo
echo "Next steps:"
echo "  ./build.sh          # build the image from the Containerfile"
echo "  ./run-daily.sh      # create and enter the day-to-day container"
echo
echo "Config written:"
grep -v '^#' "$ENV_FILE"
